apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eum9e6jpe-go 
  janus-idp.io/tekton: eum9e6jpe-go
  backstage.io/kubernetes-id: eum9e6jpe-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eum9e6jpe-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml