apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eum9e6jpe-go
  janus-idp.io/tekton: eum9e6jpe-go
  backstage.io/kubernetes-id: eum9e6jpe-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eum9e6jpe-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
