apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eum9e6jpe-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eum9e6jpe-go 
  name: eum9e6jpe-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eum9e6jpe-go 
